default_cfg:
  max_epochs: 100 
  gpus: [0]
  accelerator: 'gpu'
  strategy: 'ddp'
  log_dir: 'shapenet_log'
  dataloader: !torch.utils.data.DataLoader
    <<: ${.dataloader_cfg}
  
model: !perception3d.models.segmentation.object.pointnet2_part_seg_msg.PointNet2SegMSG
  <<: ${models.segmentation.object.pointnet2_part_seg_msg}

<<: ${optimizations.default}

dataloader_cfg:
  batch_size: 16
  num_workers: 10
  dataset: !perception3d.datasets.shapenet.ShapeNetPartDataset
    <<: ${datasets.shapenet}

train:
  <<: ${.default_cfg}
  # gradient_clip_val: 1.
  # gradient_clip_algorithm: 'norm'
  dataloader:
    dataset:
      split: 'train'
    shuffle: True
    drop_last: True
  loss_fn: !perception3d.losses.cross_entropy.CrossEntropyLoss
    
val:
  <<: ${.default_cfg}
  dataloader:
    dataset:
      split: 'val'
    shuffle: False
  loss_fn: !perception3d.losses.cross_entropy.CrossEntropyLoss

test:
  <<: ${.default_cfg}
  dataloader:
    dataset:
      split: 'test'
    shuffle: False

