dataloader_cfg:
  dataset: !perception3d.datasets.shapenet.ShapeNetPartDataset
    <<: ${..datasets.shapenet}
  batch_size: 16
  num_workers: 10

default_cfg:
  gpus: 0
  accelerator: 'gpu'
  strategy: 'ddp'
  dataloader: !torch.utils.data.DataLoader
    <<: ${.dataloader_cfg}
  metric_fn: !perception3d.metrics.classification.accuracy.AccuracyMetric
  log_dir: 'shapenet_log'


train:
  <<: ${.default_cfg}
  dataloader: !
    dataset: !
      root: 'shapenettrain'
      split: 'train'
    shuffle: True
    drop_last: True
    loss_fn: !perception3d.losses.classification.cross_entropy.CrossEntropyLoss
    
val:
  <<: ${.default_cfg}
  dataloader: !
    dataset: !
      split: 'val'
    shuffle: False
  loss_fn: !perception3d.losses.classification.cross_entropy.CrossEntropyLoss
test:
  <<: ${.default_cfg}
  dataloader: !
    dataset: !
      split: 'test'
    shuffle: False