dataloader_cfg:
  dataset: !perception3d.datasets.shapenet.ShapeNetPartDataset
    <<: ${..datasets.shapenet}
  batch_size: 16
  num_workers: 10

default_cfg:
  gpus: 0
  accelerator: 'gpu'
  strategy: 'ddp'
  dataloader: !torch.utils.data.DataLoader
    <<: ${.dataloader_cfg}

train:
  <<: ${.default_cfg}
  dataloader: !
    dataset: !
      root: 'shapenettrain'
      split: 'train'
    shuffle: True
    drop_last: True
  
val:
  <<: ${.default_cfg}
  dataloader: !
    dataset: !
      split: 'val'
    shuffle: False
  
test:
  <<: ${.default_cfg}
  dataloader: !
    dataset: !
      split: 'test'
    shuffle: False
  